export const Constants = {
    VIEW_MODEL_ATTRIBUTE: "viewModel",
	VIEW_MODEL_BIND_NAME: "viewModelBind",
	VIEW_MODEL_OFFSET: new CFrame(0.9, -1.3, -1.3),
	VIEW_MODEL_BOBBING_SPEED: 0.4,
	VIEW_MODEL_BOBBING_AMOUNT: 0.05,
	VIEW_MODEL_BOBBING_TRANSITION_SPEED: 10,
}